# Generated by Django 5.0.1 on 2024-02-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
